/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import form_ucenik.FormNoviUcenik;
import form_ucenik.FormPretragaUcenika;
import controller.ClientController;
import klase.EvidencijaVoznje;
import klase.Instruktor;
import klase.PlanCasa;
import klase.StavkaEvidencije;
import klase.Ucenik;
import form_evidencija_voznje.FormPretragaEvidencijeVoznje;
import form_plan.FormNoviPlanCasa;
import form_plan.FormPretragaPlanaCasa;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelStavkeEvidencije;
import session.Session;

/**
 *
 * @author Goca
 */
public class MainForm extends javax.swing.JFrame {

    private Instruktor ulogovani;
    private double ukupanIznos;

    
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani instruktor: " + ulogovani);
        setTitle("Klijentska forma");
        txtCenaCasa.setEditable(false);
        popuniUcenike();
        popuniPlanoveCasa();
        txtUkupanIznos.setEditable(false);
        tblStavke.setModel(new TableModelStavkeEvidencije());

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovani);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnIzracunajCenu = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        cmbPlanCasa = new javax.swing.JComboBox();
        cmbTipVoznje = new javax.swing.JComboBox();
        txtDatumCasa = new javax.swing.JFormattedTextField();
        txtCenaPoSatu = new javax.swing.JFormattedTextField();
        txtCenaCasa = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbUcenik = new javax.swing.JComboBox();
        txtBrojCasova = new javax.swing.JFormattedTextField();
        txtUkupanIznos = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviUcenik = new javax.swing.JMenuItem();
        miPretragaUcenika = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNoviPlan = new javax.swing.JMenuItem();
        miPretragaPlana = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaEV = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Evidencija voznje"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavke evidencije"));

        jLabel6.setText("Plan casa:");

        jLabel7.setText("Tip voznje:");

        jLabel8.setText("Datum casa:");

        jLabel9.setText("Cena po satu:");

        jLabel10.setText("Cena casa:");

        btnIzracunajCenu.setText("Izracunaj cenu casa");
        btnIzracunajCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajCenuActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        cmbPlanCasa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPlanCasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPlanCasaItemStateChanged(evt);
            }
        });

        cmbTipVoznje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Uvodni cas", "Osnovna voznja", "Gradska voznja", "Parkiranje i vestine", "Voznja autoput", "Nocna voznja", "Gradska voznja", "Zavrsna proba" }));

        txtDatumCasa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumCasa.setText("21.10.2025");

        txtCenaPoSatu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCenaPoSatu.setText("1200");
        txtCenaPoSatu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCenaPoSatuKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(cmbPlanCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(cmbTipVoznje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumCasa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCenaPoSatu)
                            .addComponent(txtCenaCasa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIzracunajCenu, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbPlanCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipVoznje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDatumCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCenaPoSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzracunajCenu)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCenaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj evidenciju");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Ucenik:");

        jLabel2.setText("Broj casova:");

        jLabel3.setText("Ukupan iznos:");

        cmbUcenik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtBrojCasova.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(cmbUcenik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(txtBrojCasova))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(txtUkupanIznos))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBrojCasova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu6.setText("Ucenik");

        miNoviUcenik.setText("Novi ucenik");
        miNoviUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviUcenikActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviUcenik);

        miPretragaUcenika.setText("Pretraga ucenika");
        miPretragaUcenika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaUcenikaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaUcenika);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Plan casa");

        miNoviPlan.setText("Novi plan");
        miNoviPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviPlanActionPerformed(evt);
            }
        });
        jMenu8.add(miNoviPlan);

        miPretragaPlana.setText("Pretraga plana");
        miPretragaPlana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPlanaActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaPlana);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Evidencija voznje");

        miPretragaEV.setText("Pretraga evidencije");
        miPretragaEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaEVActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaEV);

        jMenuBar1.add(jMenu9);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUlogovani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviUcenikActionPerformed
       FormNoviUcenik novaForma = new FormNoviUcenik();
        novaForma.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        novaForma.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            popuniUcenike(); 
        }

        @Override
        public void windowClosing(WindowEvent e) {
            popuniUcenike(); 
        }
    });
    novaForma.setVisible(true);
        
    }//GEN-LAST:event_miNoviUcenikActionPerformed

    private void miPretragaUcenikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaUcenikaActionPerformed
        FormPretragaUcenika pretraga = new FormPretragaUcenika();
        pretraga.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pretraga.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                popuniUcenike(); 
            }

            @Override
            public void windowClosing(WindowEvent e) {
                popuniUcenike(); 
            }
        });
        pretraga.setVisible(true);        

    }//GEN-LAST:event_miPretragaUcenikaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNoviPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviPlanActionPerformed
        new FormNoviPlanCasa(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviPlanActionPerformed

    private void miPretragaPlanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPlanaActionPerformed
        new FormPretragaPlanaCasa(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaPlanaActionPerformed

    private void miPretragaEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaEVActionPerformed
        new FormPretragaEvidencijeVoznje(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaEVActionPerformed

    private void btnIzracunajCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajCenuActionPerformed

        if (txtCenaPoSatu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti cenu casa!");
            return;
        }

        PlanCasa pc = (PlanCasa) cmbPlanCasa.getSelectedItem();
        double cenaPoSatu = Double.parseDouble(txtCenaPoSatu.getText());

        if (cenaPoSatu < 1000 || cenaPoSatu > 2000) {
            JOptionPane.showMessageDialog(this, "Cena po satu mora biti izmedju 1000din i 2000din!");
            return;
        }

        txtCenaCasa.setText(String.valueOf(pc.getTrajanjeUSatima() * cenaPoSatu));

    }//GEN-LAST:event_btnIzracunajCenuActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        try {
            if (txtDatumCasa.getText().isEmpty() || txtCenaCasa.getText().isEmpty()
                    || txtCenaPoSatu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti datum i cenu casa!");
                return;
            }

            PlanCasa pc = (PlanCasa) cmbPlanCasa.getSelectedItem();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumCasa = sdf.parse(txtDatumCasa.getText());
            String tipVoznje = (String) cmbTipVoznje.getSelectedItem();
            double cenaCasa = Double.parseDouble(txtCenaCasa.getText());
            double cenaPoSatu = Double.parseDouble(txtCenaPoSatu.getText());

            if (!datumCasa.after(new Date())) {
                JOptionPane.showMessageDialog(this, "Datum casa mora biti posle danasnjeg dana!");
                return;
            }

            StavkaEvidencije se = new StavkaEvidencije(null, -1, datumCasa,
                    pc.getTrajanjeUSatima(), tipVoznje, cenaCasa, cenaPoSatu, pc);

            TableModelStavkeEvidencije tm = (TableModelStavkeEvidencije) tblStavke.getModel();
            tm.dodajStavku(se);

            ukupanIznos = tm.vratiUkupanIznos();
            txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");

        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeEvidencije tm = (TableModelStavkeEvidencije) tblStavke.getModel();
            tm.obrisiStavku(row);
            ukupanIznos = tm.vratiUkupanIznos();
            txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "din");
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (txtBrojCasova.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti broj casova!");
            return;
        }

        try {
            Ucenik ucenik = (Ucenik) cmbUcenik.getSelectedItem();
            int brojCasova = Integer.parseInt(txtBrojCasova.getText());
            TableModelStavkeEvidencije tm = (TableModelStavkeEvidencije) tblStavke.getModel();

            EvidencijaVoznje ev = new EvidencijaVoznje(-1, ukupanIznos, false,
                    brojCasova, false, ucenik, ulogovani, tm.getLista());

            ClientController.getInstance().addEvidencijaVoznje(ev);
            txtBrojCasova.setText("");
            txtUkupanIznos.setText("");
            ukupanIznos = 0;
            tm.getLista().clear();
            tm.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana evidencija!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtCenaPoSatuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCenaPoSatuKeyReleased
        txtCenaCasa.setText("");
    }//GEN-LAST:event_txtCenaPoSatuKeyReleased

    private void cmbPlanCasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPlanCasaItemStateChanged
        if (cmbPlanCasa.getSelectedItem() != null) {
            txtCenaCasa.setText("");
        }
    }//GEN-LAST:event_cmbPlanCasaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzracunajCenu;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbPlanCasa;
    private javax.swing.JComboBox cmbTipVoznje;
    private javax.swing.JComboBox cmbUcenik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviPlan;
    private javax.swing.JMenuItem miNoviUcenik;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaEV;
    private javax.swing.JMenuItem miPretragaPlana;
    private javax.swing.JMenuItem miPretragaUcenika;
    private javax.swing.JTable tblStavke;
    private javax.swing.JFormattedTextField txtBrojCasova;
    private javax.swing.JTextField txtCenaCasa;
    private javax.swing.JFormattedTextField txtCenaPoSatu;
    private javax.swing.JFormattedTextField txtDatumCasa;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void popuniUcenike() {
        try {
            ArrayList<Ucenik> ucenici = ClientController.getInstance().getAllUcenik();

            cmbUcenik.removeAllItems();

            for (Ucenik ucenik : ucenici) {
                cmbUcenik.addItem(ucenik);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniPlanoveCasa() {
        try {
            ArrayList<PlanCasa> planoviCasa = ClientController.getInstance().getAllPlanCasa();

            cmbPlanCasa.removeAllItems();

            for (PlanCasa planCasa : planoviCasa) {
                cmbPlanCasa.addItem(planCasa);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
